theme: minima
author: Gao-Garrix
title: Welcome to Gao-Garrix's homepage!
description: This is Gao-Garrix's personal website.Here you can find my blog, projects, and contact information.
email: junnmail@163.com

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css: class
    line_numbers: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include processing
include:
  - _pages

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Categories
    url: /categories.html
  - title: About
    url: /about.html
  - title: Contact
    url: /contact.html
